deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u toto@cpfd.co.za,Admin@2000 ftp.cpfd.co.za; mirror -Rev . ./ --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  